LayoutNhom08/LayoutNhom08/Areas/Admin/Controllers/DanhmucSanphamController.cs
using System;
using System.Collections.Generic;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LayoutNhom08.Models;
namespace LayoutNhom8.Areas.Admin.Controllers
{
    public class DanhmucSanphamController : Controller
    {
        private ShopMotoBikes db = new ShopMotoBikes();

        // GET: Admin/DanhMucs
        public ActionResult Index()
        {
            return View(db.DanhMucs.ToList());
        }

        // GET: Admin/DanhMucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // GET: Admin/DanhMucs/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDM,TenDM,MoTa")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                db.DanhMucs.Add(danhMuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(danhMuc);
        }

        // GET: Admin/DanhMucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // POST: Admin/DanhMucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDM,TenDM,MoTa")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(danhMuc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(danhMuc);
        }

        // GET: Admin/DanhMucs/Delete/5
        public ActionResult Delete(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // POST: Admin/DanhMucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                DanhMuc danhMuc = db.DanhMucs.Find(id);
                db.DanhMucs.Remove(danhMuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                //Không hiểu sao nó không đi vào cái này khi xóa các danh mục có chứa sản phẩm nên mình nghĩ vẫn là do script
                ViewBag.Error = "Lỗi: " + ex.Message;
                return View("Index");
            }
           
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/DanhmucSanpham/Create.cshtml
@model LayoutNhom08.Models.DanhMuc

@{

    ViewBag.Title = "Thêm danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="chitiet">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <b>Tên danh mục:</b>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        @Html.EditorFor(model => model.TenDM, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenDM, "", new { @class = "text-danger" })<br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <b>Mô tả danh mục: </b>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control", @cols = 35, @rows = 5 } })
                        @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="row mt-5">
                    <div class="col-12 text-center">
                        <button type="submit" class="btn btn-success">
                            Thêm
                        </button> &nbsp; | &nbsp;

                        @Html.ActionLink("Hủy", "Index")

                    </div>
                    <br />

                </div>

            </div>
        </div>
}

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/DanhmucSanpham/Delete.cshtml
@model LayoutNhom08.Models.DanhMuc

@{

    ViewBag.Title = "Bạn chắc chắn muốn xóa danh mục " + Model.TenDM + " ?";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}



<div class="chitiet2">
    <div class="container">
        <div class="row ">
            <div class="col-4 text-center">
                <b> Mã danh mục:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.MaDM)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b>Tên danh mục: </b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.TenDM)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b>Mô tả danh mục:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.MoTa)
            </div>
        </div>
        <div class="row mt-5">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="col-md-offset-2 col-md-12 text-center">
                    <button type="submit" class="btn btn-danger">
                        Xóa
                    </button> &nbsp; | &nbsp;

                    @Html.ActionLink("Hủy", "Index")
                </div>
                <br />
            }
        </div>

        @if (ViewBag.Error != null)
        {
            <br />
            <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
        }

    </div>
</div>

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/DanhmucSanpham/Details.cshtml
@model LayoutNhom08.Models.DanhMuc

@{
    ViewBag.Title = "Chi tiết danh mục sản phẩm";
    
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="chitiet2">
    <div class="container">
        <div class="row ">
            <div class="col-4 text-center">
                <b> Mã danh mục:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.MaDM)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b>Tên danh mục: </b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.TenDM)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b>Mô tả danh mục:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.MoTa)
                @*Html.Raw("<pre>" + Html.Encode(Model.MoTa) + "</pre>")*@
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-12 text-center">
                @Html.ActionLink("Quay lại", "Index")
            </div>
        </div>
    </div>
</div>
       

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/DanhmucSanpham/Edit.cshtml
@model LayoutNhom08.Models.DanhMuc

@{
    ViewBag.Title = "Sửa danh mục sản phẩm";

    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="chitiet">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MaDM)
            <div class="form-group mt-3">
                <b>Mã danh mục :</b>
                @Html.DisplayFor(model => model.MaDM)
                <br />
            </div>

            <div class="form-group mt-3">
                <b>Tên danh mục:</b>
                <div class="col-md-12">
                    @Html.EditorFor(model => model.TenDM, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenDM, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mt-3">
                <b> Mô tả:</b>
                <div class="col-md-12">
                    @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control", @cols = 35, @rows = 5 } })
                    @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mt-5 ">
                <div class="col-md-offset-2 col-md-12 text-center">
                    <button type="submit" class="btn btn-warning">
                        Sửa
                    </button> &nbsp; | &nbsp;

                    @Html.ActionLink("Hủy", "Index")
                </div>
            </div>
        </div>
    }
</div>

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/DanhmucSanpham/Index.cshtml
@model IEnumerable<LayoutNhom08.Models.DanhMuc>
@{
    ViewBag.Title = "Danh mục sản phẩm";
   
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section CSSPartial{
    <link href="~/Areas/Admin/Assets/css/table.css" rel="stylesheet">
}
<div class="row">
    <div class="col-lg-12 mb-2 ">
        <button type="button" class="btn btn-success">
            <a href="@Url.Action("Create","DanhmucSanpham")" style="color:white;">
                <i class="bi bi-plus-square-dotted"></i>
                Thêm danh mục
            </a>
        </button>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <table class="table table-bordered table-striped table-hover">
            <thead>
                <tr class="text-center">
                    <th>Mã danh mục</th>
                    <th>Tên danh mục</th>
                    <th colspan="3">Hành động</th>
                </tr>
            </thead>

            <tbody>

                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <th>@Html.DisplayFor(modelItem => item.MaDM)</th>
                        <td>@Html.DisplayFor(modelItem => item.TenDM)</td>
                        <td title="Xem chi tiết" class="see-details"> <a href="@Url.Action("Details","DanhmucSanpham",new {id = item.MaDM})"><i class="bi bi-eye-fill"></i></a></td>
                        <td title="Sửa danh mục" class="edit"> <a href="@Url.Action("Edit","DanhmucSanpham",new {id = item.MaDM})"><i class="bi bi-pencil-fill"></i></a></td>
                        <td title="Xóa danh mục" class="remove"> <a href="@Url.Action("Delete","DanhmucSanpham",new {id = item.MaDM})"><i class="bi bi-trash-fill"></i></a></td>
                    </tr>
                }
                </tbody>
            
            </table>
            
    </div>
</div>