LayoutNhom08/LayoutNhom08/Areas/Admin/Controllers/DangnhapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayoutNhom8.Areas.Admin.Controllers
{
    public class DangnhapController : Controller
    {
        // GET: Admin/Dangnhap
        public ActionResult Index()
        {
            return View();
        }
    }
}

LayoutNhom08/LayoutNhom08/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayoutNhom08.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        public ActionResult XemSanPhamTheoDanhMuc()
        {
            return View();
        }
        public ActionResult ChiTietSanPham()
        {
            return View();
        }
        public ActionResult GioHang()
        {
            return View();
        }
        public ActionResult DatHang()
        {
            return View();
        }
        public ActionResult TimKiemSanPham()
        {
            return View();
        }
    }
}

LayoutNhom08/LayoutNhom08/Controllers/TaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayoutNhom08.Controllers
{
    public class TaiKhoanController : Controller
    {
        // GET: TaiKhoan
        public ActionResult DangKy()
        {
            return View();
        }
        public ActionResult DangNhap()
        {
            return View();
        }
        public ActionResult DoiMatKhau()
        {
            return View();
        }
        public ActionResult SuaTaiKhoan()
        {
            return View();
        }
    }
}

LayoutNhom08/LayoutNhom08/Views/Shared/_Footer.cshtml
<!-- ======= Footer ======= -->
<div class="grocino-footer2" style="background-image: url(/wwwroot/img/slide/footer_bg.jpg); background-repeat: no-repeat; background-size: contain; background-position: center;">
    <div id="grocino-footer" class="footer-container">
        <div class="grocino-footer-row">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-6 mr-auto">
                        <div class="grocino-second-row-item">
                            <a href="index.html">
                                <img src="~/wwwroot/img/slide/logo2.jpg" alt="HoangCau" title="HoangCau" class="img-fluid logo" />
                            </a>
                            <p>
                                HỆ THỐNG XE MÁY HOÀNG CẦU chuyên cung cấp các dòng xe Honda, Yamaha, SYM, Suzuki, xe
                                nhập khẩu,.... chính hãng, cam kết mang đến những sản phẩm, phụ tùng chất lượng nhất đến
                                tay người tiêu dùng.
                            </p>
                        </div>
                    </div>

                    <div>
                        <div class="footer_showroom">
                            <h4>HỆ THỐNG SHOWROOM</h4>
                            <ul>
                                <li>
                                    <a href="@Url.Action("Index","Home")">
                                        <strong>YAMAHA TOWN HOÀNG CẦU - 08 </strong><br>
                                        ☎:0274 6568 777 📞: 0989 882 545<br>
                                        ĐC: Số 189, Đường Nguyễn Trãi, P. Dĩ An, Thị Xã Dĩ An, Tỉnh Bình Dương.
                                    </a></a>
                                </li>
                                <br>
                                <li>
                                    <a href="@Url.Action("Index","Home")">
                                        <strong>HOÀNG CẦU CHI NHÁNH 2 </strong><br>
                                        ☎:02854 432 212 📞: 0984 741 875 <br>
                                        ĐC: Số 7-9, QL 1K, P. Linh Xuân, Thủ Đức, Tp. HCM.
                                    </a></a>
                                </li>
                                <br>
                                <li>
                                    <a href="@Url.Action("Index","Home")">
                                        <strong>HOÀNG CẦU CHI NHÁNH 3</strong><br>
                                        ☎:02854 034 142 📞: 0989 882 545<br>
                                        ĐC: 123/2A Ngô Chí Quốc, KP.2, P.Bình Chiểu, Q.Thủ Đức, TP.HCM.
                                    </a></a>
                                </li>
                                <br>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="grocino-second-row-item">
                            <h4>LIÊN KẾT NHANH</h4>
                            <ul>
                                <li> @Html.ActionLink("Trang chủ", "Index", "Home")</li>
                                <li>@Html.ActionLink("Đăng nhập", "DangNhap", "TaiKhoan")</li>
                                <li>@Html.ActionLink("Đăng ký", "DangKy", "TaiKhoan")</li>
                                <li>@Html.ActionLink("Sủa tài khoản", "SuaTaiKhoan", "TaiKhoan")</li>
                                <li>@Html.ActionLink("Đổi mật khẩu", "DoiMatKhau", "TaiKhoan")</li>
                                <li>@Html.ActionLink("Đăng xuất", "Index", "Home")</li>
                                <li>@Html.ActionLink("Giỏ hàng", "GioHang", "SanPham")</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div>
        <div class="copyright">
            Copyright  <i class="far fa-copyright"></i> 2021 Nhóm 8 - Lập trình ASP.NET
        </div>
    </div>
</div>
<!-- End Footer -->

LayoutNhom08/LayoutNhom08/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">


<!-- Mirrored from ocsolutions.co.in/grocerino/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 12 Oct 2021 14:16:18 GMT -->
<head>

    <title>Hệ Thống Xe máy Hoàng Cầu</title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, shrink-to-fit=9" />

    <meta name="description" content="Home supermarket" />

    <meta name="author" content="Home Grocerino" />

    @Html.Partial("_Style")


</head>

<body class="grocino-home">

    <!-- JS -->
    @Html.Partial("_Script")


    <!-- Top header start -->
    @Html.Partial("_Navbar");
    <!-- Start Hero Slide-->
    <!-- slider -->
    @RenderSection("slider", required: false)
    <!-- since -->
    @RenderBody()
    <!-- footer -->
    <!-- End Hero Slide-->
    <!-- About us start -->
    <!-- About us end -->
    <!-- grocino footer start -->
    <!-- ======= Footer ======= -->
    @Html.Partial("_Footer")
    <!-- End Footer -->
    <!-- mobile menu End -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-GF3SVYD2YD"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-GF3SVYD2YD');
    </script>


</body>


<!-- Mirrored from ocsolutions.co.in/grocerino/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 12 Oct 2021 14:17:01 GMT -->
</html>

LayoutNhom08/LayoutNhom08/Views/Shared/_Navbar.cshtml
<header id="header" class="fixed-top">
    <div class="p1">
        <div class="container d-flex align-items-center">
            <a href="@Url.Action("Index","Home")" class="logo me-auto"><img src="~/wwwroot/img/logos/logo1.png" alt="" width="100%" height="100%"></a>

        </div>
    </div>
    <div class="p2">
        <ul id="menu">
            <div class="inner">
                <div class="header-navbar-wrapper">
                    <div class="header-navbar text-right">
                        <ul class="no-bullets">
                            <li><a href="@Url.Action("Index", "Home")"><span>TRANG CHỦ</span></a></li>
                            <li><a href="@Url.Action("XemSanPhamTheoDanhMuc", "SanPham")"><span>XE NHẬP KHẨU</span></a></li>
                            <li><a href="@Url.Action("XemSanPhamTheoDanhMuc", "SanPham")"><span>HONDA</span></a></li>
                            <li><a href="@Url.Action("XemSanPhamTheoDanhMuc", "SanPham")"><span>YAMAHA</span></a></li>
                            <li><a href="@Url.Action("XemSanPhamTheoDanhMuc", "SanPham")"><span>SUZUKI</span></a></li>
                            <li><a href="@Url.Action("XemSanPhamTheoDanhMuc", "SanPham")"><span>SYM</span></a></li>

                        </ul>
                    </div>
                </div>
            </div>
    </div></div>
    <nav id="navbar" class="navbar order-last order-lg-0">


        <a class="nav-link scrollto search">
            <form>
                <input type="text" name="txtKeyword" style="border-radius: 15px;" placeholder="Tìm kiếm ..." />
                <i class="fas fa-search icons" style="font-size: 20px;margin-left: 0px; "></i>
            </form>
        </a>

        <!-- <li><a class="nav-link scrollto" href="#">
                <i class="fas fa-user icons"></i>
            </a>
        </li> -->


        <ul class="dropdown" style="margin-left: -20px;">
            <a href="#"><span><i class="fas fa-user icons"></i></span></a>
            <ul>
                <li>@Html.ActionLink("ĐĂNG NHẬP", "Dangnhap", "TaiKhoan")</li>
                <li>@Html.ActionLink("ĐĂNG KÝ", "DangKy", "TaiKhoan")</li>
                <li>@Html.ActionLink("ĐỔI MẬT KHẨU", "DoiMatKhau", "TaiKhoan")</li>
                <li>@Html.ActionLink("SỬA TÀI KHOẢN", "SuaTaiKhoan", "TaiKhoan")</li>
                <li>@Html.ActionLink("ĐĂNG XUẤT", "Index", "Home")</li>

            </ul>
        </ul>

        <a href="@Url.Action("GioHang","SanPham")"><i class="fas fa-cart-plus icons"></i></a>
        <!-- .navbar -->
    </nav>

</header>

LayoutNhom08/LayoutNhom08/Views/Shared/_Script.cshtml
<script src="~/wwwroot/assets/vendor/aos/aos.js"></script>
<script src="~/wwwroot/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/wwwroot/assets/vendor/glightbox/js/glightbox.min.js"></script>
<script src="~/wwwroot/assets/vendor/purecounter/purecounter.js"></script>
<script src="~/wwwroot/assets/vendor/swiper/swiper-bundle.min.js"></script>
<script src="~/wwwroot/assets/js/main.js"></script>

<script src="~/wwwroot/assets/js/popper.js"></script>

<script src="~/wwwroot/assets/js/jquery.js"></script>

<script src="~/wwwroot/assets/js/bootstrap.js"></script>

<script src="~/wwwroot/assets/js/dropdown.js"></script>

<script src="~/wwwroot/assets/js/semantic.js"></script>

<script src="~/wwwroot/assets/js/owl.carousel.js"></script>

<script src="~/wwwroot/assets/js/swiper.min.js"></script>

<script src="~/wwwroot/assets/js/vejcustome.js"></script>

<script src="~/wwwroot/assets/js/counter.js"></script>
<script src="~/wwwroot/assets/js/main.js"></script>
<!-- JS -->
<script src="~/wwwroot/assets/vendor/aos/aos.js"></script>
<script src="~/wwwroot/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/wwwroot/assets/vendor/glightbox/js/glightbox.min.js"></script>
<script src="~/wwwroot/assets/vendor/purecounter/purecounter.js"></script>
<script src="~/wwwroot/assets/vendor/swiper/swiper-bundle.min.js"></script>

LayoutNhom08/LayoutNhom08/Views/Shared/_Style.cshtml
<!-- Favicon Icon -->

<link rel="icon" type="image/png" href="~/wwwroot/img/logos/logo1.jpg" />

<!-- Stylesheets -->

<link href="~/wwwroot/assets/css/bootstrap.min.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/owl.carousel.css" rel="stylesheet" />

<link rel="stylesheet" href="~/wwwroot/assets/unicons/css/unicons.css" />

<link href="~/wwwroot/css/style.css" rel="stylesheet" />

<link href="~/wwwroot/css/responsive.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/semantic.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/animate.min.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/swiper.min.css" rel="stylesheet" />

<link href="~/wwwroot/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">

<link href="~/wwwroot/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">

<!-- Fonts -->

<link href="~/wwwroot/assets/fonts/style.css" rel="stylesheet" />