LayoutNhom08/LayoutNhom08/Areas/Admin/Controllers/SanphamController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LayoutNhom08.Models;


namespace LayoutNhom8.Areas.Admin.Controllers
{
    public class SanphamController : Controller
    {
        private ShopMotoBikes db = new ShopMotoBikes();

        // GET: Admin/Hangs
        public ActionResult Index()
        {
            var hangs = db.Hangs.Include(h => h.DanhMuc);
            return View(hangs.ToList());
        }

        // GET: Admin/Hangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hang hang = db.Hangs.Find(id);
            if (hang == null)
            {
                return HttpNotFound();
            }
            return View(hang);
        }

        // GET: Admin/Hangs/Create
        public ActionResult Create()
        {
            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM");

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaHang,MaDM,TenHang,ThuongHieu,LoaiXe,GiaTien,MoTaHang,MauSac,SoLuong,Anh")] Hang hang)
        {
            //Làm theo kiểu này mình cũng không hiểu lắm nó lại mất hình ảnh khi mà thiếu dữ liệu
            if (ModelState.IsValid)
            {
                hang.Anh = null;
                var f = Request.Files["ImageFilesss"];
                if (f != null && f.ContentLength > 0)
                {
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UploadPath = Server.MapPath("~/wwwroot/img/sanpham/" + FileName);

                    f.SaveAs(UploadPath);

                    hang.Anh = FileName;
                }
                db.Hangs.Add(hang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM");
            return View(hang);



            //Cái này làm theo bài tập của cô nhưng không hiểu sao nó chạy ra luôn index và không có thông báo gì
            //theo mình nghĩ là do phần file script không có thư mục script nhúng vào
            /* try
             {
                 if (ModelState.IsValid)
                 { 
                     hang.Anh = null;
                     var f = Request.Files["ImageFilesss"];
                     if (f != null && f.ContentLength > 0)
                     {
                         string FileName = System.IO.Path.GetFileName(f.FileName);
                         string UploadPath = Server.MapPath("~/wwwroot/img/sanpham/" + FileName);

                         f.SaveAs(UploadPath);

                         hang.Anh = FileName;
                     }
                     db.Hangs.Add(hang);
                     db.SaveChanges();
                 }
                 return RedirectToAction("Index");
             }
             catch (Exception ex)
             {
                 ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM");
                 ViewBag.Error = "Có lỗi xảy ra ! " + ex.Message;
                 return View(hang);
             }*/
        }



        // GET: Admin/Hangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hang hang = db.Hangs.Find(id);
            if (hang == null)
            {
                return HttpNotFound();
            }
          
            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", hang.MaDM);
            return View(hang);
        }

        // POST: Admin/Hangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaHang,MaDM,TenHang,ThuongHieu,LoaiXe,GiaTien,MoTaHang,MauSac,SoLuong,Anh")] Hang hang)
        {

            if (ModelState.IsValid)
            {
                var f = Request.Files["ImageFilesss"];
                if (f != null && f.ContentLength > 0)
                {
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UploadPath = Server.MapPath("~/wwwroot/img/sanpham/" + FileName);

                    f.SaveAs(UploadPath);

                    hang.Anh = FileName;
                }
                db.Entry(hang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM");
            return View(hang);
            

            //Cái này mình nghĩ tương tự với creat như mình đã ghi chú
        }

        // GET: Admin/Hangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hang hang = db.Hangs.Find(id);
            if (hang == null)
            {
                return HttpNotFound();
            }
            return View(hang);
        }

        // POST: Admin/Hangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hang hang = db.Hangs.Find(id);
            db.Hangs.Remove(hang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LayoutNhom08/LayoutNhom08/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayoutNhom08.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        public ActionResult XemSanPhamTheoDanhMuc()
        {
            return View();
        }
        public ActionResult ChiTietSanPham()
        {
            return View();
        }
        public ActionResult GioHang()
        {
            return View();
        }
        public ActionResult DatHang()
        {
            return View();
        }
        public ActionResult TimKiemSanPham()
        {
            return View();
        }
    }
}

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/Sanpham/Create.cshtml
@model LayoutNhom08.Models.Hang

@{
    ViewBag.Title = "Thêm sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="chitiet">
@using (Html.BeginForm("Create", "Sanpham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="col-md-12 text-center">
                <p><img id="hienThiAnh" width="150px" src="~/wwwroot/img/sanpham/no-image-news.png" /></p>
                <p><label for="loadFile" style="cursor:pointer;"><b>Chọn file ảnh</b></label></p>
                <p><input name="ImageFilesss" type="file" id="loadFile" style="display:none;" onchange="eventLoadFile(event)" /></p>  
            </div>
        </div>
        <div class="form-group">
            <b>Tên hàng:</b>
            <div class="col-md-12">
                @Html.EditorFor(model => model.TenHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-1">
            <b>Tên danh mục:</b>
            <div class="col-md-12">
                @Html.DropDownList("MaDM", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-1">
            <b>Thương hiệu:</b>
            <div class="col-md-12">
                @Html.EditorFor(model => model.ThuongHieu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThuongHieu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-1">
            <b> Loại xe: </b>
            <div class="col-md-12">
                @Html.EditorFor(model => model.LoaiXe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoaiXe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-1">
            <b>Giá tiền: </b>
            <div class="col-md-12">
                @Html.EditorFor(model => model.GiaTien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaTien, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group mt-1">
            <b>Màu sắc:</b>
            <div class="col-md-12">
                @Html.EditorFor(model => model.MauSac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MauSac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-1">
            <b>Số lượng: </b>
            <div class="col-md-12">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
            
        </div>
        <div class="form-group mt-1">
            <b> Mô tả hàng:</b>
            <div class="col-md-12">
                @Html.EditorFor(model => model.MoTaHang, new { htmlAttributes = new { @class = "form-control", @cols = 35, @rows = 5 } })
                @Html.ValidationMessageFor(model => model.MoTaHang, "", new { @class = "text-danger" })
            </div>
            <br />
        </div>
        <div class="form-group mt-1">
            <div class="col-md-offset-2 col-md-12 text-center">
                <button type="submit" class="btn btn-success">
                    Thêm
                </button> &nbsp; | &nbsp;

                @Html.ActionLink("Hủy", "Index")
            </div>
            <br />
        </div>

    </div>
}



   
</div>

    <script>
        var eventLoadFile = function (event) {

            var file = document.getElementById("loadFile").value;
            var ext = file.substring(file.lastIndexOf('.') + 1);
            if (ext == "") return true;
            if (ext == "gif" || ext == "GIF" || ext == "PNG" || ext == "png" || ext == "jpg" || ext == "JPG" || ext == "bmp" || ext == "BMP") {
                var imagessssssss = document.getElementById('hienThiAnh');
                imagessssssss.src = URL.createObjectURL(event.target.files[0]);
                return true;
            }
            else {
                document.getElementById("loadFile").value = null;
                alert("Chỉ upload file ảnh!");
                fup.focus();
                return false;
            }
        };

    </script>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/Sanpham/Delete.cshtml
@model LayoutNhom08.Models.Hang

@{
    ViewBag.Title = "Bạn có chắc chắn muốn xóa sản phẩm "+ Model.TenHang + " ?";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}





<div class="chitiet2">
    <div class="container">
        <div class="row ">
            <div class="col-12 text-center">
                @{
                    string ImagePath = "";
                    if (Model.Anh != null) { ImagePath = "~/wwwroot/img/sanpham/" + Model.Anh; }
                    else { ImagePath = "~/wwwroot/img/sanpham/no-image-news.png"; }
                }
                <img src="@Url.Content(ImagePath)" width="200" class="img-thumbnail" />
                <br />
                @Html.HiddenFor(modelItem => Model.Anh)

            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Mã sản phẩm:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.MaHang)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Tên sản phẩm:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.TenHang)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Tên danh mục:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.DanhMuc.TenDM)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Thương hiệu:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.ThuongHieu)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Loại xe:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.LoaiXe)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Giá tiền:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.GiaTien)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Màu sắc:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.MauSac)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Số lượng:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.MaHang)
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-4 text-center">
                <b>Mô tả sản phẩm:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.MoTaHang)
            </div>
        </div>
        <div class="row mt-5 mb-3">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="col-md-offset-2 col-md-12 text-center">
                    <button type="submit" class="btn btn-danger">
                        Xóa
                    </button> &nbsp; | &nbsp;

                    @Html.ActionLink("Hủy", "Index")
                </div>
                <br />
            }
        </div>
    </div>



   
</div>

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/Sanpham/Details.cshtml
@model LayoutNhom08.Models.Hang

@{
    ViewBag.Title = "Chi tiết sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="chitiet2">
    <div class="container">
        <div class="row ">
            <div class="col-12 text-center">
                @{
                    string ImagePath = "";
                    if (Model.Anh != null) { ImagePath = "~/wwwroot/img/sanpham/" + Model.Anh; }
                    else { ImagePath = "~/wwwroot/img/sanpham/no-image-news.png"; }
                }
                <img src="@Url.Content(ImagePath)" width="200" class="img-thumbnail" />
                <br />
                @Html.HiddenFor(modelItem => Model.Anh)

            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Mã sản phẩm:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.MaHang)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Tên sản phẩm:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.TenHang)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Tên danh mục:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.DanhMuc.TenDM)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Thương hiệu:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.ThuongHieu)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Loại xe:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.LoaiXe)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Giá tiền:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.GiaTien)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Màu sắc:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.MauSac)
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 text-center">
                <b> Số lượng:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.MaHang)
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-4 text-center">
                <b>Mô tả sản phẩm:</b>
            </div>
            <div class="col-8 text-left">
                @Html.DisplayFor(model => model.MoTaHang)
            </div>
        </div>
        <div class="row mt-5 mb-3">
            <div class="col-12 text-center">
                @Html.ActionLink("Quay lại", "Index")
            </div>
        </div>
    </div>
</div>

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/Sanpham/Edit.cshtml
@model LayoutNhom08.Models.Hang

@{
    ViewBag.Title = "Sửa sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="chitiet">
    @using (Html.BeginForm("Edit", "Sanpham", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.MaHang)
            <div class="form-group">
                <div class="col-md-12 text-center">
                    @{
                        string ImagePath = "";
                        if (Model.Anh != null) { ImagePath = "~/wwwroot/img/sanpham/" + Model.Anh; }
                        else { ImagePath = "~/wwwroot/img/sanpham/no-image-news.png"; }
                    }
                    <img id="hienThiAnh" class="img-rounded" alt="Ảnh" width="180" 
                         src="@Url.Content(@ImagePath)" />
                    <p><label for="loadFile" style="cursor: pointer;">Chọn file ảnh</label></p>
                    <input name="ImageFile" id="loadFile" type="file" style="display: none;" onchange="eventLoadFile(event)" />
                    @Html.HiddenFor(model => model.Anh, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                <b>Tên hàng:</b>
                <div class="col-md-12">
                    @Html.EditorFor(model => model.TenHang, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenHang, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mt-2">
                <b>Tên danh mục:</b>
                <div class="col-md-12">
                    @Html.DropDownList("MaDM", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mt-2">
                <b>Thương hiệu:</b>
                <div class="col-md-12">
                    @Html.EditorFor(model => model.ThuongHieu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ThuongHieu, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mt-2">
                <b> Loại xe: </b>
                <div class="col-md-12">
                    @Html.EditorFor(model => model.LoaiXe, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LoaiXe, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mt-1">
                <b>Giá tiền: </b>
                <div class="col-md-12">
                    @Html.EditorFor(model => model.GiaTien, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GiaTien, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group mt-2">
                <b>Màu sắc:</b>
                <div class="col-md-12">
                    @Html.EditorFor(model => model.MauSac, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MauSac, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group mt-2">
                <b>Số lượng: </b>
                <div class="col-md-12">
                    @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control", data_val_number = "Số sản phẩm phải là số !" } })
                    @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group mt-2">
                <b> Mô tả hàng:</b>
                <div class="col-md-12">
                    @Html.EditorFor(model => model.MoTaHang, new { htmlAttributes = new { @class = "form-control", @cols = 35, @rows = 5 } })
                    @Html.ValidationMessageFor(model => model.MoTaHang, "", new { @class = "text-danger" })
                </div>
                <br />
            </div>
            <div class="form-group mt-2">
                <div class="col-md-offset-2 col-md-12 text-center">
                    <button type="submit" class="btn btn-warning">
                        Sửa
                    </button> &nbsp; | &nbsp;

                    @Html.ActionLink("Hủy", "Index")
                </div>
                <br />
            </div>

        </div>
    }




</div>

<script>
        var eventLoadFile = function (event) {

            var file = document.getElementById("loadFile").value;
            var ext = file.substring(file.lastIndexOf('.') + 1);
            if (ext == "") return true;
            if (ext == "gif" || ext == "GIF" || ext == "PNG" || ext == "png" || ext == "jpg" || ext == "JPG" || ext == "bmp" || ext == "BMP") {
                var imagessssssss = document.getElementById('hienThiAnh');
                imagessssssss.src = URL.createObjectURL(event.target.files[0]);
                return true;
            }
            else {
                document.getElementById("loadFile").value = null;
                alert("Chỉ upload file ảnh!");
                fup.focus();
                return false;
            }
        };

</script>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/Sanpham/Index.cshtml
@model IEnumerable<LayoutNhom08.Models.Hang>
@{
    ViewBag.Title = "Danh sách sản phẩm";

    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


@section CSSPartial{
    <link href="~/Areas/Admin/Assets/css/table.css" rel="stylesheet">
}

    <div class="row">
        <div class="col-lg-12 mb-2 ">
            <button type="button" class="btn btn-success">
                <a href="@Url.Action("Create","Sanpham")" style="color:white;">
                    <i class="bi bi-plus-square-dotted"></i>
                    Thêm sản phẩm
                </a>
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-bordered table-center table-striped table-hover">
                <thead>
                    <tr class="text-center">
                        <th>Mã sản phẩm</th>
                        <th>Ảnh</th>
                        <th>Tên tên sản phẩm</th>
                        <th>Tên danh mục</th>
                        <th>Số lượng còn</th>
                        <th colspan="3">Hành động</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="text-center" style="text-align: center;">
                            <td style="text-align: center;"> @Html.DisplayFor(modelItem => item.MaHang)</td>
                            <td>
                                @{
                                    string ImagePath = "";
                                    if (item.Anh != null) { ImagePath = "~/wwwroot/img/sanpham/" + item.Anh; }
                                    else { ImagePath = "~/wwwroot/img/sanpham/no-image-news.png"; }
                                }
                                <img src="@Url.Content(ImagePath)" width="60" class="img-thumbnail" />
                                <br />
                                @Html.HiddenFor(modelItem => item.Anh)
                            </td>
                            <td style="text-align: center;">@Html.DisplayFor(modelItem => item.TenHang)</td>
                            <td style="text-align: center;"> @Html.DisplayFor(modelItem => item.DanhMuc.TenDM)</td>
                            <td style="text-align: center;">@Html.DisplayFor(modelItem => item.SoLuong)</td>
                            <td title="Xem chi tiết" class="see-details"><a href="@Url.Action("Details","Sanpham",new {id = item.MaHang})"><i class="bi bi-eye-fill"></i></a></td>
                            <td title="Sửa sản phẩm" class="edit"><a href="@Url.Action("Edit","Sanpham",new {id = item.MaHang})"><i class="bi bi-pencil-fill"></i></a></td>
                            <td title="Xóa sản phẩm" class="remove"><a href="@Url.Action("Delete","Sanpham",new {id = item.MaHang})"><i class="bi bi-trash-fill"></i></a></td>
                        </tr>

                    }
                </tbody>
            </table>
        </div>
    </div>