LayoutNhom08/LayoutNhom08/Areas/Admin/Controllers/DangnhapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayoutNhom8.Areas.Admin.Controllers
{
    public class DangnhapController : Controller
    {
        // GET: Admin/Dangnhap
        public ActionResult Index()
        {
            return View();
        }
    }
}

LayoutNhom08/LayoutNhom08/Areas/Admin/Controllers/TaikhoanController.cs
using LayoutNhom08.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LayoutNhom8.Areas.Admin.Controllers
{
    public class TaikhoanController : Controller
    {
        private ShopMotoBikes db = new ShopMotoBikes();

        // GET: Admin/TaiKhoans
        public ActionResult Index()
        {
            return View(db.TaiKhoans.ToList());
            
        }

        // GET: Admin/TaiKhoans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTK,HoTen,TenDN,MatKhau,Quyen,TrangThai,SoDienThoai,Email")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taiKhoan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(taiKhoan);
        }

        // GET: Admin/TaiKhoans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: Admin/TaiKhoans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            db.TaiKhoans.Remove(taiKhoan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ThongtinDangnhap()
        {
            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/Shared/_FooterAdmin.cshtml
<footer id="footer" class="footer">
    <div class="copyright">
        Copyright <strong> &copy; </strong> <b> Nhóm 8 - Lập trình ASP.NET </b>
    </div>
</footer>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center">
    <i class="bi bi-arrow-up-short"></i>
</a>

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/Shared/_HeaderAdmin.cshtml
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="@Url.Action("Index","Home")" class="logo d-flex align-items-center">
            <img src="~/Areas/Admin/Assets/img/header_1.jpg" alt="">
            <span class="d-none d-lg-block">HOÀNG CẦU</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">
            <li class="nav-item dropdown pe-3">

                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-person-fill" style="font-size: 30px;"></i>
                    <span class="d-none d-md-block dropdown-toggle ps-2">
                        NHÓM 8
                    </span>
                </a><!-- End Profile Iamge Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>Nhóm 8</h6>
                        <span>Lập trình ASP.NET</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="@Url.Action("ThongtinDangnhap","Taikhoan")">
                            <i class="bi bi-person"></i>
                            <span>Tài khoản</span>
                        </a>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="@Url.Action("Index","Dangnhap")">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Đăng xuất</span>
                        </a>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->

</header>

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- Thiết lập chung -->
    @{
        Html.RenderPartial("_TitleHeadAdmin");
    }


    <!-- Template Main CSS File -->
    <link href="~/Areas/Admin/Assets/css/style.css" rel="stylesheet">
    <link href="~/Areas/Admin/Assets/css/footer.css" rel="stylesheet">
    <link href="~/Areas/Admin/Assets/css/main.css" rel="stylesheet">
    <link href="~/Areas/Admin/Assets/css/header.css" rel="stylesheet">
    <link href="~/Areas/Admin/Assets/css/slide-bar.css" rel="stylesheet">

    <!-- Template CSSPartial File -->
    @RenderSection("CSSPartial", required: false)


</head>

<body>
   
    <!-- ======= Header ======= -->
    @{
        Html.RenderPartial("_HeaderAdmin");
    }
    <!-- End Header -->
    <!-- ======= Sidebar ======= -->
    @{
        Html.RenderPartial("_SidebarAdmin");
    }
    <!-- End Sidebar-->
    <!-- ======= Main ======= -->
    <main id="main" class="main">
        <div class="container">
            @{
                Html.RenderPartial("_PageTitleAdmin");
            }
            <!-- End Page Title -->

            
                @RenderBody()
            
        </div>
    </main>
    <!-- End #main -->
    <!-- ======= Footer ======= -->
    @{
        Html.RenderPartial("_FooterAdmin");
    }
    <!-- End Footer -->
    <!-- Vendor JS Files -->
    <script src="~/Areas/Admin/Assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>

    <!-- Template Main JS File -->
    <script src="~/Areas/Admin/Assets/js/main.js"></script>

</body>
</html>

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/Shared/_PageTitleAdmin.cshtml
<div class="pagetitle">
    <h1 style="text-align: center;"> @ViewBag.Title</h1>
    @*<nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item active">
                    <a href="@Url.Action("Index","Home")">
                        <b><i class="bi bi-house"></i></b>&nbsp;
                    </a>
                </li>
                <li class="breadcrumb-item active">

                        @if (@ViewBag.Link != "Thông tin đăng nhập")
                        {
                            <a href="@Url.Action( "Index" , ViewBag.Name )">
                                @ViewBag.Link
                            </a>
                        }
                        else
                        {
                            <a href="#">
                                @ViewBag.Link
                            </a>
                        }

                </li>
            </ol>
        </nav>*@
</div>

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/Shared/_SidebarAdmin.cshtml
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Home" ? "active": "" )" href="@Url.Action("Index","Home")">
                <i class="bi bi-grid"></i>
                <span>Thống kê</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "DanhmucSanpham" ? "active": "" ) " href="@Url.Action("Index","DanhmucSanpham")">
                <i class="bi bi-folder2-open"></i>
                <span>Quản lý danh mục</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Sanpham" ? "active": "" ) " href="@Url.Action("Index","Sanpham")">
                <i class="bi bi-box-seam"></i>
                <span>Quản lý sản phẩm</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Donhang" ? "active": "" ) " href="@Url.Action("Index","Donhang")">
                <i class="bi bi-bag"></i>
                <span>Quản lý đơn hàng</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @((ViewContext.RouteData.Values["Controller"].ToString() == "Taikhoan" && ViewContext.RouteData.Values["Action"].ToString() == "Index" )   ? "active": "" ) " href="@Url.Action("Index","Taikhoan")">
                <i class="bi bi-person-circle"></i>
                <span>Quản lý tài khoản</span>
            </a>
        </li>



        <li class="nav-heading">Pages</li>

        <li class="nav-item">
            <a class="nav-link @(ViewContext.RouteData.Values["Action"].ToString() == "ThongtinDangnhap" ? "active": "" ) " href="@Url.Action("ThongtinDangnhap","Taikhoan")">
                <i class="bi bi-file-earmark"></i>
                <span>Thông tin</span>
            </a>
        </li><!-- End Blank Page Nav -->

    </ul>

</aside>

LayoutNhom08/LayoutNhom08/Areas/Admin/Views/Shared/_TitleHeadAdmin.cshtml
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1.0" name="viewport">

<link rel="shortcut icon" href="//theme.hstatic.net/200000281285/1000677821/14/favicon.png?v=689" type="image/png" />
<title>Hệ Thống Xe máy Hoàng Cầu</title>
<meta content="" name="description">
<meta content="" name="keywords">
<link rel="icon" type="image/png" href="~/Areas/Admin/Assets/img/logo1.jpg" />


<!-- Google Fonts -->
<link href="https://fonts.gstatic.com" rel="preconnect">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet">

<!-- Vendor CSS Files -->
<link href="~/Areas/Admin/Assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="~/Areas/Admin/Assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">